### ISSUE TITLE
absl conflicts with tcmalloc

### ISSUE THREAD

**Issue by kirakira** [abseil/abseil-cpp#215]
My project depends on [gperftools](https://github.com/gperftools/gperftools) and absl. When I updated absl library past https://github.com/abseil/abseil-cpp/commit/bd5a2bba8f4238db2e06c99ac808fc8327dec2a0 I'm getting ODR errors:
```
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/gperftools/_objs/tcmalloc/external/gperftools/src/base/dynamic_annotations.pic.o: multiple definition of 'RunningOnValgrind'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/dynamic_annotations/external/com_google_absl/absl/base/dynamic_annotations.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/gperftools/_objs/tcmalloc/external/gperftools/src/base/dynamic_annotations.pic.o: multiple definition of 'ValgrindSlowdown'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/dynamic_annotations/external/com_google_absl/absl/base/dynamic_annotations.pic.o: previous definition here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The dependency chain is

absl::Mutex -> absl/debugging:symbolize -> absl/base:malloc_internal -> absl/base:dynamic_annotations -> absl/base/dynamic_annotations.cc

where the first segment is introduced by https://github.com/abseil/abseil-cpp/commit/bd5a2bba8f4238db2e06c99ac808fc8327dec2a0. gperftools also has a [dynamic_annotations.c](https://github.com/gperftools/gperftools/blob/master/src/base/dynamic_annotations.c) which exports the same set of functions.

**Comment by derekmauro** [comment]
Duplicate of #122
