### ISSUE TITLE
Debug build failure: gtest_label_1081 used but not defined

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#159]
ubuntu 16.04, default gcc 5.4

```
git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp
bazel build ...
```

```
ERROR: abseil-cpp/absl/strings/BUILD.bazel:235:1: C++ compilation of rule '//absl/strings:string_view_test' failed (Exit 1)
In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:58:0,
                 from absl/strings/string_view_test.cc:28:
absl/strings/string_view_test.cc: In member function 'virtual void {anonymous}::NonNegativeLenTest_NonNegativeLen_Test::TestBody()':
absl/strings/string_view_test.cc:38:40: error: label 'gtest_label_1081' used but not defined
 #define ABSL_EXPECT_DEATH_IF_SUPPORTED EXPECT_DEATH_IF_SUPPORTED
                                        ^
absl/strings/string_view_test.cc:1080:3: note: in expansion of macro 'ABSL_EXPECT_DEATH_IF_SUPPORTED'
   ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("xyz", -1),
   ^
absl/strings/string_view_test.cc: In member function 'virtual void {anonymous}::LenExceedsMaxSizeTest_LenExceedsMaxSize_Test::TestBody()':
absl/strings/string_view_test.cc:38:40: error: label 'gtest_label_1092' used but not defined
 #define ABSL_EXPECT_DEATH_IF_SUPPORTED EXPECT_DEATH_IF_SUPPORTED
                                        ^
absl/strings/string_view_test.cc:1091:3: note: in expansion of macro 'ABSL_EXPECT_DEATH_IF_SUPPORTED'
   ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("", max_size + 1),
   ^
```

git bisect shows 99477fa9f1e89a7d8253c8aeee331864710d080c is the first bad commit.

This is a quick fix:

```
diff --git a/absl/strings/str_cat_test.cc b/absl/strings/str_cat_test.cc
index e9d67690..9c6e4df1 100644
--- a/absl/strings/str_cat_test.cc
+++ b/absl/strings/str_cat_test.cc
@@ -405,8 +405,7 @@ TEST(StrAppend, Death) {
   std::string s = "self";
   // on linux it's "assertion", on mac it's "Assertion",
   // on chromiumos it's "Assertion ... failed".
-  ABSL_EXPECT_DEBUG_DEATH(absl::StrAppend(&s, s.c_str() + 1),
-                          "ssertion.*failed");
+  ABSL_EXPECT_DEBUG_DEATH(absl::StrAppend(&s, s.c_str() + 1), "ssertion.*failed");
   ABSL_EXPECT_DEBUG_DEATH(absl::StrAppend(&s, s), "ssertion.*failed");
 }
 #endif  // GTEST_HAS_DEATH_TEST
diff --git a/absl/strings/string_view_test.cc b/absl/strings/string_view_test.cc
index fffa7b99..9fecf655 100644
--- a/absl/strings/string_view_test.cc
+++ b/absl/strings/string_view_test.cc
@@ -1077,8 +1077,7 @@ TEST(HugeStringView, TwoPointTwoGB) {
 
 #if !defined(NDEBUG) && !defined(ABSL_HAVE_STD_STRING_VIEW)
 TEST(NonNegativeLenTest, NonNegativeLen) {
-  ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("xyz", -1),
-                                 "len <= kMaxSize");
+  ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("xyz", -1), "len <= kMaxSize");
 }
 
 TEST(LenExceedsMaxSizeTest, LenExceedsMaxSize) {
@@ -1088,8 +1087,7 @@ TEST(LenExceedsMaxSizeTest, LenExceedsMaxSize) {
   absl::string_view ok_view("", max_size);
 
   // Adding one to the max should trigger an assertion.
-  ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("", max_size + 1),
-                                 "len <= kMaxSize");
+  ABSL_EXPECT_DEATH_IF_SUPPORTED(absl::string_view("", max_size + 1), "len <= kMaxSize");
 }
 #endif  // !defined(NDEBUG) && !defined(ABSL_HAVE_STD_STRING_VIEW)
 
```

**Comment by derekmauro** [comment]
Thanks for the report. I've managed to reproduce this in a VM. I have no idea why it doesn't reproduce on any of the compilers I normally use.

I have a different fix in mind though:
`#define ABSL_EXPECT_DEATH_IF_SUPPORTED EXPECT_DEATH_IF_SUPPORTED`
becomes
`#define ABSL_EXPECT_DEATH_IF_SUPPORTED(s, r) EXPECT_DEATH_IF_SUPPORTED(s, r)`

**Comment by derekmauro** [comment]
Fixed by d8cfe9f2a77fbee02c09642491e62a3f3677e0f6.
