### ISSUE TITLE
linking fails when compiled with clang and -fsanitize=undefined

### ISSUE THREAD

**Issue by rojkov** [abseil/abseil-cpp#841]
The int128 support in SimpleAtoi introduced in abseil/abseil-cpp@4b915e7 triggers this bug in Clang: [__int128_t multiply with -fsanitize=undefined fails to link (undefined reference to __muloti4)](https://bugs.llvm.org/show_bug.cgi?id=16404)

```
2020-11-05T15:34:46.1334065Z ERROR: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/envoy/test/integration/BUILD:254:14: Linking of rule '@envoy//test/integration:hotrestart_test' failed (Exit 1): clang failed: error executing command 
2020-11-05T15:34:46.1335612Z   (cd /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/execroot/envoy && \
2020-11-05T15:34:46.1336305Z   exec env - \
2020-11-05T15:34:46.1336703Z     BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
2020-11-05T15:34:46.1337306Z     BAZEL_LINKLIBS=-l%:libstdc++.a \
2020-11-05T15:34:46.1337873Z     BAZEL_LINKOPTS=-lm \
2020-11-05T15:34:46.1338251Z     CC=clang \
2020-11-05T15:34:46.1338572Z     CXX=clang++ \
2020-11-05T15:34:46.1338900Z     ENVOY_ASAN=1 \
2020-11-05T15:34:46.1339237Z     ENVOY_UBSAN_VPTR=1 \
2020-11-05T15:34:46.1339644Z     PATH=/usr/sbin:/usr/bin:/sbin:/bin:/opt/llvm/bin \
2020-11-05T15:34:46.1340034Z     PWD=/proc/self/cwd \
2020-11-05T15:34:46.1340759Z   /opt/llvm/bin/clang @bazel-out/k8-dbg/bin/external/envoy/test/integration/hotrestart_test-2.params)
2020-11-05T15:34:46.1341345Z Execution platform: @rbe_ubuntu_clang//config:platform
2020-11-05T15:34:46.1341798Z ld.lld: error: undefined symbol: __muloti4
2020-11-05T15:34:46.1342380Z >>> referenced by int128_have_intrinsic.inc:251 (external/com_google_absl/absl/numeric/int128_have_intrinsic.inc:251)
2020-11-05T15:34:46.1343451Z >>>               bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/numbers.pic.o:(absl::operator*(absl::int128, absl::int128))
2020-11-05T15:34:46.1344374Z clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Steps to reproduce the bug**

I stumble upon this issue when running Envoy's unit tests:
1. git clone https://github.com/envoyproxy/envoy.git && cd envoy
1. update Abseil to the latest master in `bazel/repository_locations.bzl`;
1. run `ci/run_envoy_docker.sh 'ci/do_ci.sh bazel.compile_time_options'`

**What version of Abseil are you using?**

The latest master.

**What operating system and version are you using**

Ubuntu 18.04.5 LTS

**What compiler and version are you using?**

clang version 10.0.0

**What build system are you using?**

bazel 3.6.0

**Additional context**

In the referenced LLVM bug it's suggested to link with compiler-rt which contains the implementation of `__muloti4`, but it's an optional LLVM component. Is it possible to include `__muloti4` in Abseil?

**Comment by derekmauro** [comment]
I think we also ran into this problem. I think the better solution is to simply have Envoy build with `-fsanitize-link-c++-runtime` (`--copt=-fsanitize-link-c++-runtime --linkopt=-fsanitize-link-c++-runtime`) when using sanitizers.

**Comment by derekmauro** [comment]
The fix went into Envoy.

**Comment by GregBowyer** [comment]
@derekmauro How did you solve this?

**Comment by derekmauro** [comment]
Add `-fsanitize-link-c++-runtime` to your compile/link options.

**Comment by stweil** [comment]
I have the same problem when building [tesseract](https://github.com/tesseract-ocr/tesseract/) on Debian GNU Linux with clang++-11 and sanitizers after an update from abseil 20200923.3 to 210324.1. Adding `-fsanitize-link-c++-runtime` does not help:

```
$ clang++ -g -O2 -D_GLIBCXX_DEBUG -fsanitize=fuzzer-no-link,address,undefined -fsanitize-address-use-after-scope -Wall -fsanitize-link-c++-runtime -std=c++20 -o baseapi_test unittest/baseapi_test-baseapi_test.o  ./.libs/libabseil.a ./.libs/libtesseract_training.a ./.libs/libgtest.a ./.libs/libgtest_main.a -lpthread ./.libs/libtesseract.a -lcurl -larchive -llept
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 8ea
/usr/bin/ld: DWARF error: could not find variable specification at offset 95e
/usr/bin/ld: DWARF error: could not find variable specification at offset 9b8
/usr/bin/ld: DWARF error: could not find variable specification at offset a12
/usr/bin/ld: DWARF error: could not find variable specification at offset a55
/usr/bin/ld: DWARF error: could not find variable specification at offset a98
./.libs/libabseil.a(libabseil_la-numbers.o): in function `absl::lts_20210324::operator*(absl::lts_20210324::int128, absl::lts_20210324::int128)':
/home/stweil/src/github/tesseract-ocr/tesseract/bin/ndebug/clang,sanitize/../../../abseil/absl/numeric/int128_have_intrinsic.inc:251: undefined reference to `__muloti4'
/usr/bin/ld: /home/stweil/src/github/tesseract-ocr/tesseract/bin/ndebug/clang,sanitize/../../../abseil/absl/numeric/int128_have_intrinsic.inc:251: undefined reference to `__muloti4'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by derekmauro** [comment]
`-fsanitize-link-c++-runtime` should only be necessary if you are building with `clang`. From what I've read it should be implied by `clang++`.

If you supply a full reproduction (meaning a full list of commands to get into the exact state your machine is in) someone might look into it.

**Comment by stweil** [comment]
Is a GitHub action sufficient? See [workflow file](https://github.com/stweil/tesseract/actions/runs/845345270/workflow) and [log output](https://github.com/stweil/tesseract/runs/2591320991?check_suite_focus=true). Abseil is used for the Tesseract unit tests, so the build error happens in the step "Make and run Unit Tests".

**Comment by stweil** [comment]
@derekmauro, here is another current CI result which shows this issue: https://github.com/stweil/tesseract/actions/runs/857320116. So basically you simply can fork the `tesseract` repository and run the GitHub action. Do you need more information how to reproduce the issue?

**Comment by derekmauro** [comment]
@stweil - I played with the tesseract project as best I could. I was able to get by the error you are getting by adding `'LDFLAGS=-lc++ -lc++abi'`, but there are some other problems, which may or may not be related. You will have to install libc++ first to do this.

I don't know whether or not linking libc++ and libc++abi is safe in your current configuration. It looks like you are currently using libstdc++ for this build.

We do our sanitizer builds entirely with libc++. You can take a look at https://github.com/abseil/abseil-cpp/blob/master/ci/linux_clang-latest_libcxx_asan_bazel.sh if you need ideas.

**Comment by stweil** [comment]
I already tried linking with libc++ and added libc++abi now, too, but still get an undefined reference to `__muloti4`. My build environment is Debian bullseye.

**Comment by mmatrosov** [comment]
Could you guys please share how did you address the problem? I have the same issue, though in the code unrelated to abseil.

**Comment by keith** [comment]
upstream issue https://github.com/llvm/llvm-project/issues/16778

I found that passing `-lubsan` works in some cases too

**Comment by keith** [comment]
or `-rtlib=compiler-rt`
