### ISSUE TITLE
The 20211102.0 version uses unpublished `GTEST_FLAG_GET` macro from `googletest`

### ISSUE THREAD

**Issue by PawelWMS** [abseil/abseil-cpp#1063]
**Describe the bug**

In the 20211102.0 version of `abseil-cpp` some of [the test code started using the `GTEST_FLAG_GET` macro](https://github.com/abseil/abseil-cpp/commit/89c531c1e0d7372e2e7029f072a35495c5447d61). This causes the following build failures when attempting a CMake build with a pre-installed, latest released version (1.11.0) of `googletest`:

```
[ 47%] Built target absl_cord_internal_test"
absl/strings/cord_ring_test.cc: In function 'absl::lts_20211102::{anonymous}::Composition absl::lts_20211102::{anonymous}::RandomComposition()':"
absl/strings/cord_ring_test.cc:278:35: error: 'random_seed' was not declared in this scope; did you mean 'random_r'?"
  278 |   RandomEngine rng(GTEST_FLAG_GET(random_seed));"
      |                                   ^~~~~~~~~~~"
      |                                   random_r"
absl/strings/cord_ring_test.cc:278:20: error: 'GTEST_FLAG_GET' was not declared in this scope; did you mean 'GTEST_FLAG'?"
  278 |   RandomEngine rng(GTEST_FLAG_GET(random_seed));"
      |                    ^~~~~~~~~~~~~~"
      |                    GTEST_FLAG"
```

After taking a look at the [GoogleTest GitHub repository](https://github.com/google/googletest) it seems, that the changes introducing this macro are only present in the `main` branch but haven't been packed into an official release, yet.

**Steps to reproduce the bug**

1. Install the 1.11.0 version of GoogleTest.
2. Configure the `abseil-cpp` build with CMake (version >= 3.20.0) and the `-DABSL_FIND_GOOGLETEST=ON -DABSL_USE_EXTERNAL_GOOGLETEST=ON -DBUILD_TESTING=ON` options.
3. Build with `make`.

**What version of Abseil are you using?**

20211102.0

**What operating system and version are you using**

Docker container on a Ubuntu 18.04 host.

**What compiler and version are you using?**

gcc: 9.1.0

**What build system are you using?**

cmake: 3.21.4
make: 4.2.1

**Additional context**

None.

**Comment by PawelWMS** [comment]
Now I've also noticed that this version of `abseil-cpp` is also relying on `::testing::Conditional`, which is GTest matcher, which also [didn't make it to any official release](https://github.com/google/googletest/commit/8306020a3e9eceafec65508868d7ab5c63bb41f7), yet. After providing a dummy macro for `GTEST_FLAG_GET` and removing the use of `::testing::Conditional` the project built along with all tests, so I think those are the only two.

**Comment by derekmauro** [comment]
The [June 2022 release](https://github.com/abseil/abseil-cpp/releases/tag/20220623.0) addresses this issue. A coordinated GoogleTest release was done to ensure compatibility, and our release documentation has been updated so ensure future releases are coordinated as well.

**Comment by WildSouthern** [comment]
I fell behind is it corrected?
