### ISSUE TITLE
MSVC 16.2, C++17, and /permissive- fails to build

### ISSUE THREAD

**Issue by wesleygriffin** [abseil/abseil-cpp#357]
Here is a minimal repro: https://github.com/wesleygriffin/absl-msvc-16-2

I don't see any duplicate issues opened or closed., although perhaps #356 looks related?

I compile with `/permissive-` to put MSVC into standards compliance mode: https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019 as my main project is cross-platform.

The failure I'm getting is in absl/container/internal/compressed_tuple.h:

~~~
C:\Users\WesleyGriffin\Active\wesleygriffin\absl-msvc-16-2\out\build\x64-Debug\_deps\abseil-src\absl\container\internal\compressed_tuple.h(224): error C3546: '...': there are no parameter packs available to expand
  C:\Users\WesleyGriffin\Active\wesleygriffin\absl-msvc-16-2\out\build\x64-Debug\_deps\abseil-src\absl\container\internal\inlined_vector.h(436): note: see reference to class template instantiation 'absl::container_internal::CompressedTuple<std::allocator<T>,unsigned __int64>' being compiled
          with
          [
              T=Foo
          ]
  C:\Users\WesleyGriffin\Active\wesleygriffin\absl-msvc-16-2\out\build\x64-Debug\_deps\abseil-src\absl\container\inlined_vector.h(73): note: see reference to class template instantiation 'absl::inlined_vector_internal::Storage<T,8,A>' being compiled
          with
          [
              T=Foo,
              A=std::allocator<Foo>
          ]
  C:\Users\WesleyGriffin\Active\wesleygriffin\absl-msvc-16-2\test.cpp(10): note: see reference to class template instantiation 'absl::InlinedVector<Foo,8,std::allocator<T>>' being compiled
          with
          [
              T=Foo
          ]
C:\Users\WesleyGriffin\Active\wesleygriffin\absl-msvc-16-2\out\build\x64-Debug\_deps\abseil-src\absl\container\internal\compressed_tuple.h(228): error C3520: 'Vs': parameter pack must be expanded in this context
~~~

If I don't use `/permissive-` then the repro compiles cleanly.

**Comment by pps83** [comment]
Same here, basic use of `absl::flat_hash_map` in [VS 2019](https://visualstudio.microsoft.com/vs/) results in compilation errors:

> absl\container\internal\compressed_tuple.h(225,54): error C3546: '...': there are no parameter packs available to expand

The problem was introduced by c6c3c1b49.

Removing `/permissive-` makes VS2019 compile the code, but it doesn't link because apparently abseil containers aren't header-only (unlike boost::container::flat_map, flat_hash::hash_map and other libs from the web).
**Edit:** Just tried to make it compile with abseil, and I had to add 32 .cc files to my project. I'm shocked

**Comment by CJ-Johnson** [comment]
@sbenzaquen Have you been able to take a look at this?
