### ISSUE TITLE
[Bug]: 20260526.0 requires `-Wno-invalid-partial-specialization` with clang < 16.0.0

### ISSUE THREAD

**Issue by bmclarnon** [abseil/abseil-cpp#2073]
### Describe the issue

[absl/strings/internal/stl_type_traits.h](https://github.com/abseil/abseil-cpp/blob/5650e9cf76d3be4318d5fa3af38ee483ddfd5e4a/absl/strings/internal/stl_type_traits.h) fails to compile with clang < 16.0.0 due to `IsBaseOfSpecializationImpl` and `IsConvertibleToSpecializationImpl` template partial specialization not being more specialized than the primary template.

```
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:92:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
struct IsBaseOfSpecializationImpl<
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:82:8: note: template is declared here
struct IsBaseOfSpecializationImpl : std::false_type {};
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:117:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
struct IsBaseOfSpecializationImpl<
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:82:8: note: template is declared here
struct IsBaseOfSpecializationImpl : std::false_type {};
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:170:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
struct IsConvertibleToSpecializationImpl<
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:160:8: note: template is declared here
struct IsConvertibleToSpecializationImpl : std::false_type {};
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:194:8: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
struct IsConvertibleToSpecializationImpl<
       ^
bazel-out/k8-fastbuild/bin/external/abseil-cpp+/absl/strings/../../../../../../../external/abseil-cpp+/absl/strings/internal/stl_type_traits.h:160:8: note: template is declared here
struct IsConvertibleToSpecializationImpl : std::false_type {};
       ^
4 errors generated.
```

### Steps to reproduce the problem

`MODULE.bazel`:

```
bazel_dep(name = "abseil-cpp", version = "20260526.0")
bazel_dep(name = "toolchains_llvm", version = "1.6.0")

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
lvm.toolchain(
    name = "llvm_toolchain",
    llvm_version = "15.0.6",
)
use_repo(llvm, "llvm_toolchain")

register_toolchains("@llvm_toolchain//:all")
```

Build command:

```
USE_BAZEL_VERSION=8.6.0 bazelisk build --cxxopt=-std=c++17 @abseil-cpp//absl/strings
```

### What version of Abseil are you using?

20260526.0

Failure does not occur with 20260107.1.

### What operating system and version are you using?

Debian GNU/Linux rodete

### What compiler and version are you using?

```
clang version 15.0.6
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/bmclarnon/.cache/bazel/_bazel_bmclarnon/a2f6e1039076f20f8b6258df9ec69b11/external/toolchains_llvm++llvm+llvm_toolchain/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/15
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/15
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

I also reproduced the issue with clang 14.0.0.  Building with clang 16.0.0 succeeded.

### What build system are you using?

bazel 8.6.0

**Comment by bmclarnon** [comment]
I narrowed the breakage down to https://github.com/abseil/abseil-cpp/commit/9cb62a03a4f11e20294aecbb26711014f37c11da. Applying the following patch "fixes" the issue, though I have no idea why `absl::void_t` and `std::void_t` are treated differently:

```patch
--- absl/strings/internal/stl_type_traits.h
+++ absl/strings/internal/stl_type_traits.h
@@ -91,7 +91,7 @@
 template <typename C, template <typename, typename, typename> class T>
 struct IsBaseOfSpecializationImpl<
     C, T,
-    std::void_t<typename C::key_type, typename C::key_compare,
+    absl::void_t<typename C::key_type, typename C::key_compare,
                 typename C::allocator_type>>
     : std::is_base_of<C, T<typename C::key_type, typename C::key_compare,
                            typename C::allocator_type>> {};
@@ -115,10 +115,10 @@
 template <typename C,
           template <typename, typename, typename, typename, typename> class T>
 struct IsBaseOfSpecializationImpl<
     C, T,
-    std::void_t<typename C::key_type, typename C::mapped_type,
+    absl::void_t<typename C::key_type, typename C::mapped_type,
                 typename C::hasher, typename C::key_equal,
                 typename C::allocator_type>>
     : std::is_base_of<C, T<typename C::key_type, typename C::mapped_type,
                            typename C::hasher, typename C::key_equal,
                            typename C::allocator_type>> {};
@@ -169,7 +169,7 @@
 template <typename C, template <typename, typename, typename> class T>
 struct IsConvertibleToSpecializationImpl<
     C, T,
-    std::void_t<typename C::key_type, typename C::key_compare,
+    absl::void_t<typename C::key_type, typename C::key_compare,
                 typename C::allocator_type>>
     : std::is_convertible<C, T<typename C::key_type, typename C::key_compare,
                                typename C::allocator_type>> {};
@@ -192,8 +192,8 @@
 template <typename C,
           template <typename, typename, typename, typename, typename> class T>
 struct IsConvertibleToSpecializationImpl<
     C, T,
-    std::void_t<typename C::key_type, typename C::mapped_type,
+    absl::void_t<typename C::key_type, typename C::mapped_type,
                 typename C::hasher, typename C::key_equal,
                 typename C::allocator_type>>
     : std::is_convertible<C, T<typename C::key_type, typename C::mapped_type,
                                typename C::hasher, typename C::key_equal,
                                typename C::allocator_type>> {};
```

Would it be safe to suppress the error on older clang versions with something like `--per_file_copt=external/abseil-cpp\+/absl/strings/internal/stl_type_traits.h@-Wno-invalid-partial-specialization`? Or is the error an indication that older versions of clang will use the wrong template specialization and cause subtle issues?

**Comment by derekmauro** [comment]
This is only used to implement a single check when using a debug build of libstdc++: https://github.com/abseil/abseil-cpp/blob/71a7f828fc4f9a0ceb40a39d8e9861db557a3df2/absl/strings/internal/str_split_internal.h#L234-L236

And just by coincidence I think it was fixed today by https://github.com/abseil/abseil-cpp/commit/71a7f828fc4f9a0ceb40a39d8e9861db557a3df2.

I don't think it is a great idea to build foreign codebases with `-Werror`. By all means use it for your own code so you don't introduce regressions, but treating every possible build warning as an error in code you don't control will frustrate you.

We actually use `--per_file_copt=external/.*@-w` for this purpose.

**Comment by bmclarnon** [comment]
Thanks, Derek. For what it's worth, I'm not using `-Werror`: clang treats `invalid-partial-specialization` as an error [by default](https://clang.llvm.org/docs/DiagnosticsReference.html#winvalid-partial-specialization), presumably because according to [temp.class.spec.match#3](https://timsong-cpp.github.io/cppwp/n4868/temp.class.spec.match#3),

> If the template arguments of a partial specialization cannot be deduced because of the structure of its template-parameter-list and the template-id, the program is ill-formed.

It's also not suppressed by `-w`. But I confirmed that it's fixed by https://github.com/abseil/abseil-cpp/commit/71a7f828fc4f9a0ceb40a39d8e9861db557a3df2, and using `-Wno-invalid-partial-specialization` is an easy work-around. Thanks!
