### ISSUE TITLE
[Bug]: Build failure affecting *BSD after Sept 2022

### ISSUE THREAD

**Issue by ryan-sg** [abseil/abseil-cpp#1518]
### Describe the issue

absl is included as a subproject for a nifty mpd shuffling client called ashuffle.  I was having some troubles building a newer version of it, and accidentally found out that an older commit of absl seemed to allow the build to work fine.

I isolated that simply trying to build absl directly with its CMake files after commit 88cc63ef739d83277b492e881be72e9069fcb1fe  fails due to the changes in fallback code around pthread-related code in sysinfo.cc

### Steps to reproduce the problem

OpenBSD 7.3 and likely -current fails to build due to the following error after commit 88cc63ef739d83277b492e881be72e9069fcb1fe, failing with:
```
00:53 ryan@build-amd64:..absl$ cd build
00:53 ryan@build-amd64:..build$ make 
[  1%] Built target log_severity
[  2%] Built target raw_logging_internal
[  3%] Built target spinlock_wait
[  3%] Building CXX object absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.o
/home/ryan/ashuffle/subprojects/absl/absl/base/internal/sysinfo.cc:450:10: error: static_cast from 'pthread_t' (aka 'pthread *') to 'pid_t' (aka 'int') is not allowed
  return static_cast<pid_t>(pthread_self());
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error 1 in . (absl/base/CMakeFiles/base.dir/build.make:104 'absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.o': cd /home/ryan/ashuffle...)
*** Error 2 in . (CMakeFiles/Makefile2:1478 'absl/base/CMakeFiles/base.dir/all': make -s -f absl/base/CMakeFiles/base.dir/build.make absl/ba...)
*** Error 2 in /home/ryan/ashuffle/subprojects/absl/build (Makefile:146 'all': make -s -f CMakeFiles/Makefile2 all)
```

I can confirm that a checkout at commit 7f3c0d781134d25b24e0b55346482a2d366bf59b  does build successfully.
Anything newer including bleeding edge hits same `static_cast from 'pthread_t'` issue

### What version of Abseil are you using?

7f3c0d781134d25b24e0b55346482a2d366bf59b builds OK
d2de53124ec55390ce1ec66fd1fbf28b5a7ec4ec hits cast error and is what ashuffle currently has pinned as subproject version.
bleeding edge commit 94b37802217a9c9bb182bd99d55096683ef45b2c still has same error as well

### What operating system and version are you using?

OpenBSD 7.3

### What compiler and version are you using?

OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.3
Thread model: posix
InstalledDir: /usr/bin

### What build system are you using?

cmake version 3.25.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

### Additional context

https://github.com/joshkunz/ashuffle/issues/207
is the original issue posted about this, before realising my muckup by not actually having the proper subproject version checked out.  If any additional information is needed I will do my best to produce it.  Thanks!

EDIT: removed backtics from around the commit hashes so they link properly, woops.

**Comment by moubctez** [comment]
Same error on NetBSD.

My quick-and-dirty fix:

```
--- absl/base/internal/sysinfo.cc.orig	2023-08-21 14:43:13.000000000 +0000
+++ absl/base/internal/sysinfo.cc
@@ -447,7 +447,7 @@ pid_t GetTID() {
 pid_t GetTID() {
   // `pthread_t` need not be arithmetic per POSIX; platforms where it isn't
   // should be handled above.
-  return static_cast<pid_t>(pthread_self());
+  return static_cast<pid_t>((intptr_t)pthread_self());
 }
 
 #endif
```

**Comment by MikaelUrankar** [comment]
Same error on FreeBSD.

**Comment by matthewjmiller1** [comment]
For [FreeBSD](https://man.freebsd.org/cgi/man.cgi?query=pthread_getthreadid_np&sektion=3&format=html), it looks like including `pthread_np.h` and calling `pthread_getthreadid_np()` gets it to build (after fixing this [bug](https://github.com/google/cctz/issues/270) in cctz's FreeBSD build). E.g.:
```
#elif defined(__FreeBSD__)

#include <pthread_np.h>

pid_t GetTID() {
  return static_cast<pid_t>(pthread_getthreadid_np());
}
```

**Comment by matthewjmiller1** [comment]
@ryan-sg may want to update the title to indicate that all *BSD builds seem broken for the 20230802.0 release to maybe get this better visibility.

**Comment by derekmauro** [comment]
I was not able to test this fix since I don't have BSDs available. Please let me know if it is not fixed.

**Comment by matthewjmiller1** [comment]
I don't think the FreeBSD fix is going to work since `pthread_getthreadid_np()` seems to have a different signature vs. Darwin. The FreeBSD API takes no parameters whereas the Darwin API takes in two parameters.
I think `__FreeBSD__` needs its own block separate from `__APPLE__` to call its version of the API.

**Comment by derekmauro** [comment]
Argh, thanks for pointing that out.

**Comment by ryan-sg** [comment]
a git checkout including b9707b7d7845f9710ae6d5906827b833fdcc2754 builds successfully on OpenBSD 7.3/amd64.  Thanks!

**Comment by Chilledheart** [comment]
Would this be backported to lts branch? I can confirm Abseil LTS 20230802 branch is broken for FreeBSD build (requiring ded2ec077 as well).

**Comment by derekmauro** [comment]
I've backported this to a new patch release: https://github.com/abseil/abseil-cpp/releases/tag/20230802.1

**Comment by spchamp** [comment]
Is there any possibility of [another patch](https://cgit.freebsd.org/ports/tree/devel/py-grpcio/files/patch-third__party_abseil-cpp_absl_time_internal_cctz_src_time__zone__format.cc) making it into the tree? from [FreeBSD ports](https://www.freshports.org/devel/py-grpcio)

**Comment by derekmauro** [comment]
> Is there any possibility of another patch making it into the tree? from FreeBSD ports

If there is another patch release I can include ded2ec077d911de647d47ab48ef3a8e24a1fb64a, but I'm not going to do one for this issue only as unfortunately we don't officially support FreeBSD.
