### PR TITLE
fixup! PR #1707: Fixup absl_random compile breakage in Apple ARM64 targets

### PR DESCRIPTION
**Pull request by Royna2544**
Use the SHELL: prefix in compile flag string to avoid passing it as quoted string
Introduced in CMake 3.12, but as CMake 3.16 is required by this project it will be ok.

According to [this link](https://cmake.org/cmake/help/latest/command/target_compile_options.html#option-de-duplication), CMake's target_compile_options ignores duplicate items, like from the quote of the link:

> While beneficial for individual options, the de-duplication step can break up option groups. For example, -option A -option B becomes -option A B. One may specify a group of options using shell-like quoting along with a SHELL: prefix.

This was our problem, -option A -option B should be there, but CMake just made it like -option A B, B was not guarded by -Xarch which led to a compilation error.

I originally tried the fix with quoting the "-option A", but it led to the quoted string passed to the compiler, and therefore ignored.
Now I am using the SHELL: suffix supported by CMake, and it shows differences:

> Current build command with quotes:
> ... -DNOMINMAX "-Xarch_x86_64 -maes" "-Xarch_x86_64 -msse4.1" ... (Wrong)

> With the SHELL: prefix applied:
> ... -DNOMINMAX -Xarch_x86_64 -maes -Xarch_x86_64 -msse4.1 ... (Correct)

### CODE REVIEW

**Comment by anpol** [comment]
For the record, 

1. The issue has been introduced by #1086
2. The second `-Xarch_x86_64` option were being removed by the CMake [option deduplication](https://cmake.org/cmake/help/latest/command/target_compile_options.html#option-de-duplication),<br> leaving the subsequent `-msse4.1` an orphan.
3. Using the `SHELL:` prefix is the correct way to suppress the option deduplication.

**Comment by ZhongRuoyu** [comment]
FYI, this broke pkgconfig file generation, as `Cflags` in `lib/pkgconfig/absl_random_internal_randen_hwaes.pc` now contain the following:

```
SHELL:-Xarch_x86_64 -maes SHELL:-Xarch_x86_64 -msse4.1 SHELL:-Xarch_arm64 -march=armv8-a+crypto
```

The `-Xarch_` flag filtering logic below (added in #1412) no longer works due to the `SHELL:` prefix:

https://github.com/abseil/abseil-cpp/blob/372124e6af36a540e74a2ec31d79d7297a831f98/CMake/AbseilHelpers.cmake#L193-L197
