### ISSUE TITLE
[Bug]: CUDA 13.3 fails to build host code that uses Abseil

### ISSUE THREAD

**Issue by fwyzard** [abseil/abseil-cpp#2075]
### Describe the issue

Building a source file that uses Abseil's `"absl/container/flat_hash_map.h"` with NVCC from CUDA 13.3.0 fails with
```
abseil-cpp/absl/container/internal/raw_hash_map.h:126:169: error: using template type parameter 'absl::lts_20250814::container_internal::IfRRef::AddPtr' after 'typename'
126 | ABSL_INTERNAL_X(insert_or_assign, insert_or_assign_impl, const &, const &,
| ^
abseil-cpp/absl/container/internal/raw_hash_map.h:126:223: error: using template type parameter 'absl::lts_20250814::container_internal::IfRRef::AddPtr' after 'typename'
126 | ABSL_INTERNAL_X(insert_or_assign, insert_or_assign_impl, const &, const &,
| ^
abseil-cpp/absl/container/internal/raw_hash_map.h:126:234: error: template argument 5 is invalid
126 | ABSL_INTERNAL_X(insert_or_assign, insert_or_assign_impl, const &, const &,
| ^
abseil-cpp/absl/container/internal/raw_hash_map.h:126:234: error: template argument 6 is invalid
abseil-cpp/absl/container/internal/raw_hash_map.h:126:236: error: template argument 1 is invalid
126 | ABSL_INTERNAL_X(insert_or_assign, insert_or_assign_impl, const &, const &,
| ^
```
and so on.

The same test builds correctly with NVCC from CUDA 13.2.

### Steps to reproduce the problem

git clone git@github.com:fwyzard/nvidia_bug_6302392.git
cd nvidia_bug_6302392
make

### What version of Abseil are you using?

Reproduced with
  - 20250814.0
  - the current HEAD, 7768e5d7dc26cda185a037c75fc6f242273e7bce

### What operating system and version are you using?

Reproduced on Ubuntu 24.04 LTS with GCC 13.4 and on RHEL 8.10 with GCC 14.2.1

### What compiler and version are you using?

NVCC from CUDA 13.3.0:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2026 NVIDIA Corporation
Built on Fri_Apr_24_07:22:02_PM_PDT_2026
Cuda compilation tools, release 13.3, V13.3.33
Build cuda_13.3.r13.3/compiler.37862127_0
```

### What build system are you using?

None.

### Additional context

The same test compiles correctly with NVCC from CUDA 13.2:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2026 NVIDIA Corporation
Built on Mon_Mar_02_09:52:23_PM_PST_2026
Cuda compilation tools, release 13.2, V13.2.51
Build cuda_13.2.r13.2/compiler.37434383_0
```

The same problem has been reported to NVIDIA and filed as [bug 6302392](https://developer.nvidia.com/bugs/6302392).

**Comment by fwyzard** [comment]
According to the discussion in NVIDIA [bug 6302392](https://developer.nvidia.com/bugs/6302392) a fix is scheduled for CUDA 13.4.
