### ISSUE TITLE
Symbol not found: _CFTimeZoneCopyDefault for simple example on MacOS.

### ISSUE THREAD

**Issue by robertnishihara** [abseil/abseil-cpp#291]
Hi! I'm running into the following issue with abseil on MacOS. Please let me know if you have suggestions for things to try.

### Environment

- MacOS 10.13.6
- **bazel version**
    ```
    $ bazel version
    INFO: Invocation ID: cacd095e-84ff-432a-afb8-c56fe7aaad9d
    Build label: 0.22.0
    Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Mon Jan 28 13:00:18 2019 (1548680418)
    Build timestamp: 1548680418
    Build timestamp as int: 1548680418
    ```
- `g++ --version`
    ```
    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 10.0.0 (clang-1000.10.44.4)
    Target: x86_64-apple-darwin17.7.0
    Thread model: posix
    ```
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### Code for Reproducing

I can reproduce this with the following three files.

The `hello_world.cc` file:
```cpp
#include "absl/time/clock.h"
#include "absl/time/time.h"

int main() {
  absl::Time t = absl::Now();
  absl::FormatTime(t);

  return(0);
}
```
The `WORKSPACE` file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_absl",
    strip_prefix = "abseil-cpp-master",
    urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
)
```
The `BUILD` file:
```
cc_binary(
  name = "hello_world",
  deps = ["@com_google_absl//absl/time"],
  srcs = ["hello_world.cc"],
)
```

### Instructions for Reproducing

First I build with

```
$ bazel build //:hello_world
INFO: Invocation ID: df8ad84b-2691-4fea-b26c-08998d0cb391
INFO: Analysed target //:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:hello_world up-to-date:
  bazel-bin/hello_world
INFO: Elapsed time: 0.142s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

Then I run it with

```
$ ./bazel-bin/hello_world
dyld: lazy symbol binding failed: Symbol not found: _CFTimeZoneCopyDefault
  Referenced from: /Users/rnishihara/abseil-example/./bazel-bin/hello_world
  Expected in: flat namespace

dyld: Symbol not found: _CFTimeZoneCopyDefault
  Referenced from: /Users/rnishihara/abseil-example/./bazel-bin/hello_world
  Expected in: flat namespace

Abort trap: 6
```

which produces the error above.

**Comment by robertnishihara** [comment]
This may be related to #283 because the example above is broken by commit 256be563447a315f2a7993ec669460ba475fa86a (it works on the prior commit).

**Comment by derekmauro** [comment]
> http_archive(
>     name = "com_google_absl",
>     strip_prefix = "abseil-cpp-master",
>     urls = ["https://github.com/abseil/abseil-cpp/archive/master.zip"],
> )

I don't recommend using master.zip to implement living at head. Bazel is going to cache some arbitrary commit and then not update. You also aren't going to know what commit you are using. Can you update to the latest version and let us know if this is still an issue?

**Comment by derekmauro** [comment]
@shaindelschwartz - I think we need the same fix in Bazel that we used for CMake in #283.

**Comment by JonathanDCohen** [comment]
This has to do with cctz not lining "-framework Foundation".  It wasn't fixed in Bazel before because it looked like the default CROSSTOOL defines this already, but taht may only be in certain versions of Bazel.  This change has to go through cctz, so I will open a corresponding pull request there.

A problem is that this doesn't reproduce, at least on my laptop which is running bazel 0.23 instead of 0.22.  I can attempt to make a corresponding change to see if it works, but it will be hard to know for sure without the ability to repro.

**Comment by robertnishihara** [comment]
@JonathanDCohen, if you have patches that might fix it, I can give them a try. I've also had trouble reproducing it on other people's laptops.

**Comment by JonathanDCohen** [comment]
@robertnishihara please check my patch to cctz.

**Comment by robertnishihara** [comment]
@JonathanDCohen I suspect I'm doing something wrong, I tried the following.

1. Clone **abseil** and switch the `WORKSPACE` file in my example above to use

    ```
    local_repository(
      name = "com_google_absl",
      path = "/Path/to/abseil-cpp",
    )
    ```

    instead of `http_archive`. This compiles and reproduces the original error.

2. Apply your patch to `cctz/BUILD` to `abseil-cpp/absl/time/internal/cctz/BUILD.bazel`.
3. Attempt to recompile my minimal example. This step failed with errors that look unrelated to your change.
    ```
    ~/abseil-example$ bazel build //:hello_world
    INFO: Invocation ID: a4e24b10-932d-4e92-8546-94b7bd5a94d3
    ERROR: /private/var/tmp/_bazel_rnishihara/3f926b72c4342b26f2cfe542346a4646/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel:55:1: no such package '@com_google_absl//': BUILD file not found on package path and referenced by '@com_google_absl//absl/time/internal/cctz:time_zone'
    ERROR: /private/var/tmp/_bazel_rnishihara/3f926b72c4342b26f2cfe542346a4646/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel:55:1: no such package '@com_google_absl//': BUILD file not found on package path and referenced by '@com_google_absl//absl/time/internal/cctz:time_zone'
    ERROR: /private/var/tmp/_bazel_rnishihara/3f926b72c4342b26f2cfe542346a4646/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel:55:1: no such package '@com_google_absl//': BUILD file not found on package path and referenced by '@com_google_absl//absl/time/internal/cctz:time_zone'
    ERROR: /private/var/tmp/_bazel_rnishihara/3f926b72c4342b26f2cfe542346a4646/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel:55:1: no such package '@com_google_absl//': BUILD file not found on package path and referenced by '@com_google_absl//absl/time/internal/cctz:time_zone'
    ERROR: Analysis of target '//:hello_world' failed; build aborted: no such package '@com_google_absl//': BUILD file not found on package path
    INFO: Elapsed time: 0.083s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
    igured)
    ```

What's the right way to try out your patch?

**Comment by JonathanDCohen** [comment]
We unfortunately use our own fork of cctz internally so you would have to manually put that patch in (absl/time/cctz)

However https://github.com/google/cctz/pull/102 fixes the problem and has been merged, and there should be a new cctz release and subsequent abseil daily release soon.  So you should get the patch in reasonably soon once we do our next daily release.

**Comment by JonathanDCohen** [comment]
Update:  We're having issues bring the change to cctz back into our internal code base, so I'm trying to find a workaround for it.  @robertnishihara have you been able to confirm the change made to cctz works?
