### ISSUE TITLE
[Bug]: Constexpr expansion compilation error with GCC's UndefinedBehaviorSanitizer

### ISSUE THREAD

**Issue by kaxub** [abseil/abseil-cpp#1634]
### Describe the issue

When building abseil with GCC with `-fsanitize=undefined`, the following compilation error occurs:
```
/abseil/absl/container/internal/raw_hash_set.h:3364:56:   in 'constexpr' expansion of 'absl::container_internal::hash_policy_traits<absl::container_internal::FlatHashMapPolicy<std::basic_string_view<char>, absl::CommandLineFlag*>, void>::get_hash_slot_fn<absl::container_internal::StringHash>()'
/abseil/absl/container/internal/hash_policy_traits.h:163:54: error: '(absl::container_internal::TypeErasedApplyToSlotFn<absl::container_internal::StringHash, std::basic_string_view<char> > == 0)' is not a constant expression
  163 |     return Policy::template get_hash_slot_fn<Hash>() == nullptr
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
make-4.3[4]: *** [absl/flags/CMakeFiles/flags_reflection.dir/build.make:66: absl/flags/CMakeFiles/flags_reflection.dir/reflection.cc.o] Error 1   
```

This code producing the error has been introduced with commit 4c7e7c7d9.

The error does *not* occur when building with no sanitizer or when building with `-fsanitize=address` or `-fsanitize=thread`.

This seems to be a known GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71962

### Steps to reproduce the problem

```
git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp
mkdir build
cd build
cmake -DCMAKE_CXX_FLAGS="-fsanitize=undefined" ..
make
```
Isolated expression from the method where the error occurs (`absl::container_internal::hash_policy_traits::get_hash_slot_fn<Hash>()`) with `-std=gnu++17 -fsanitize=undefined`: https://godbolt.org/z/8bEazf6e5

### What version of Abseil are you using?

7bd9ff910d489658da58251de1317eb3f790a2c6

### What operating system and version are you using?

Ubuntu 20.04.6 LTS

### What compiler and version are you using?

GCC 9.4.0
Also tested with GCC 13.2 on linked godbolt.

### What build system are you using?

cmake 3.16.3

**Comment by jnooree** [comment]
Same issue here.

**Comment by ptrmtrx** [comment]
@derekmauro can somebody from abseil look at it please, it blocks our development. We use google quiche that uses abseil, but we build it by gcc with undefined behavior sanitizer and it results into this bug.

**Comment by jnooree** [comment]
For a temporary workaround, I used clang  for sanitizer builds.

**Comment by ptrmtrx** [comment]
Unfortunately, t's not an option in our environment.

**Comment by derekmauro** [comment]
Sorry, this issue is not a priority for me at the moment.

**Comment by BotellaA** [comment]
Is there any update on this? Is it an abseil issue or a GCC issue?

**Comment by jnooree** [comment]
> This seems to be a known GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71962

**Comment by min-tian-thomas** [comment]
A bug of gcc yet abseil may need some workaround to avoid considering it is such a fundamental library

**Comment by BotellaA** [comment]
I had to disable sanitizer checks, which is a bad idea, but I'm not sure what else we can do...

**Comment by ptrmtrx** [comment]
We needed the ubsan in gcc, so I created a patch to fix this issue. If anybody is interested, I am posting it here. The patch is based on the commit 60d1ce99 (current master).
It just replaces raw pointers with contexpr std::optional and workarounds a gcc ubsan bug with it. std::optional is used because absl::optional is not very constexpr due to support for c++14 (which is now dropped, but I did the fix it in December).

It works for the abseil itself, built by cmake and for abseil tests. Abseil benchmarks build is not tested as they are not in cmake scripts, or I didn't find them there. So maybe an "auto" return value will need to be specified in raw_hash_set_probe_benchmark.cc.

@derekmauro feel free to use it, modify it or just be inspired by it and integrate it into master if you want to (some kind of fix in the master would make my life easier :) )

[0001-Gcc-undefined-sanitizer-compilation-fix.patch](https://github.com/user-attachments/files/18337019/0001-Gcc-undefined-sanitizer-compilation-fix.patch)

**Comment by hoyhoy** [comment]
Add `-fno-sanitize=undefined` to the end of your CXXFLAGS for abseil.  You'll still need `-fsanitized=undefined` before that so GCC will link with the proper instrumentation.

My `CXXFLAGS` look like this.   The `-fno-sanitize=undefined` (or, `-fno-sanitize=all`), must be placed sequentially _after_ the `-fsanitize` arguments...

```
/usr/bin/g++  -I./.conan2/p/b/abseid4bc16bbf42d0/b/src -m64 -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-ipa-icf -fsanitize=undefined -fno-sanitize=alignment -w -fpermissive -ggdb3 -fno-sanitize=all -g -std=c++20 -fPIC -fdiagnostics-color=always -Wall -Wextra -Wcast-qual -Wconversion-null -Wformat-security -Wmissing-declarations -Wnon-virtual-dtor -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -DNOMINMAX -MD -MT absl/log/CMakeFiles/log_initialize.dir/initialize.cc.o -MF CMakeFiles/log_initialize.dir/initialize.cc.o.d -o CMakeFiles/log_initialize.dir/initialize.cc.o -c ./.conan2/p/b/abseid4bc16bbf42d0/b/src/absl/log/initialize.cc
```

Tested with gcc 8, 9, 10, 11, 12, 13, 14, and 15....

If you're using conan builds, something like this needs to be in your profile...


```
abseil/*:tools.build:cflags=['-fno-sanitize=all', '-fsanitize=address', '-fno-omit-frame-pointer', '-fno-optimize-sibling-calls', '-fno-ipa-icf', '-fsanitize=undefined', '-fno-sanitize=alignment', '-w', '-fpermissive', '-ggdb3']
abseil/*:tools.build:cxxflags=['-fno-sanitize=all', '-fsanitize=address', '-fno-omit-frame-pointer', '-fno-optimize-sibling-calls', '-fno-ipa-icf', '-fsanitize=undefined', '-fno-sanitize=alignment', '-w', '-fpermissive', '-ggdb3']
```

**Comment by eric-riff-simplisafe** [comment]
We're facing this problem as well. 
The workaround suggested above by @hoyhoy does not work for me because it only covers the abseil build. Other packages that consume abseil (e.g. protobuf, gRPC) and up failing with the same issue. I know I can disable UB for those libraries as well, but eventually another library that depends on abseil is going to end up hitting this bug.

```
abseil/*:tools.build:cflags+=["-fno-sanitize=undefined"]
abseil/*:tools.build:cxxflags+=["-fno-sanitize=undefined"]
protobuf/*:tools.build:cflags+=["-fno-sanitize=undefined"]
protobuf/*:tools.build:cxxflags+=["-fno-sanitize=undefined"]
grpc/*:tools.build:cflags+=["-fno-sanitize=undefined"]
grpc/*:tools.build:cxxflags+=["-fno-sanitize=undefined"]
```

**Comment by nmanthey** [comment]
The same compilation failure also occurs with when adding `-fno-delete-null-pointer-checks` (independent of UBSan) on current master. The code now carries a `#pragma GCC diagnostic ignored "-Waddress"`, which silences the warning but not this constexpr error: 

```
hash_policy_traits.h: error: '(TypeErasedApplyToSlotFn<...> == 0)' is not a constant expression
```

To reproduce, we can compile flat_hash_map TU with `-std=c++17 -fno-delete-null-pointer-checks`.

The root cause is the same: GCC won't fold a function-address `== nullptr` in a constant expression; PR 71962. The flag `-fno-delete-null-pointer-checks` is used by several distros, so this problem affects normal (non-sanitizer) builds too.
 
Would a fix that removes the address-vs-nullptr comparison be acceptable? Such a fix would resolve both this UBSan and the -fno-delete-null-pointer-checks cases. We could remove the `-Waddress pragma` go away:

```
--- a/absl/container/internal/hash_policy_traits.h
+++ b/absl/container/internal/hash_policy_traits.h
@@ namespace container_internal {
+// Selects the policy-provided type-erased hash-slot function, or the generic
+// non-type-erased fallback when the policy returns nullptr.
+template <HashSlotFn kFallbackFn, HashSlotFn kPolicyFn>
+struct HashSlotFnSelector {
+  static constexpr HashSlotFn kValue = kPolicyFn;
+};
+template <HashSlotFn kFallbackFn>
+struct HashSlotFnSelector<kFallbackFn, nullptr> {
+  static constexpr HashSlotFn kValue = kFallbackFn;
+};
+
 // Defines how slots are initialized/destroyed/moved.
 template <class Policy, class = void>
   struct hash_policy_traits : common_policy_traits<Policy> {
@@ get_hash_slot_fn() {
-#if defined(__GNUC__) && !defined(__clang__)
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Waddress"
-#endif
-    return Policy::template get_hash_slot_fn<Hash, kIsDefault, kSeedShift>() ==
-                   nullptr
-               ? &hash_slot_fn_non_type_erased<Hash, kIsDefault, kSeedShift>
-               : Policy::template get_hash_slot_fn<Hash, kIsDefault,
-                                                   kSeedShift>();
-#if defined(__GNUC__) && !defined(__clang__)
-#pragma GCC diagnostic pop
-#endif
+    return HashSlotFnSelector<
+        &hash_slot_fn_non_type_erased<Hash, kIsDefault, kSeedShift>,
+        Policy::template get_hash_slot_fn<Hash, kIsDefault,
+                                          kSeedShift>()>::kValue;
   }
```


With this change, we can compile using `-fno-delete-null-pointer-checks -Werror=address` (GCC 14.2.1).

**Comment by derekmauro** [comment]
@nmanthey - I would have to test it on all supported platforms, but that seems like it should work. Let me know if you want to open a pull request or if you want me to handle it.
