### ISSUE TITLE
Build fails on CentOS 7.6

### ISSUE THREAD

**Issue by jprider63** [abseil/abseil-cpp#643]
I receive the following error when attempting to build on CentOS 7.6 via [differential-privacy](https://github.com/google/differential-privacy) (`bazel build differential_privacy/...`): 
```
ERROR: /home/users/james/.cache/bazel/_bazel_james/ddd7f7278576f5cf8af1b5fe5af5ab65/external/com_google_absl/absl/random/internal/BUILD.bazel:294:1: C++ compilation of rule '@com_google_absl//absl/random/internal:randen_hwaes_impl' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 31 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_absl/absl/random/internal/randen_hwaes.cc:264:0:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/wmmintrin.h:34:3: error: #error "AES/PCLMUL instructions not enabled"
 # error "AES/PCLMUL instructions not enabled"
   ^
external/com_google_absl/absl/random/internal/randen_hwaes.cc: In function '{anonymous}::Vector128 {anonymous}::AesRound(const {anonymous}::Vector128&, const {anonymous}::Vector128&)':
external/com_google_absl/absl/random/internal/randen_hwaes.cc:304:67: error: '_mm_aesenc_si128' was not declared in this scope
   return Vector128(_mm_aesenc_si128(state.data(), round_key.data()));
                                                                   ^
external/com_google_absl/absl/random/internal/randen_hwaes.cc:305:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-pass-failed" [enabled by default]
```

```
$ cat /etc/system-release
CentOS Linux release 7.6.1810
```

From `/proc/cpuinfo`: 
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke spec_ctrl intel_stibp flush_l1d
```

This may be related to #137, but the error is different. Do you have any suggestions?

**Comment by derekmauro** [comment]
I took a look at this today. It looks like hardware acceleration is completely broken on Linux x86_64 under Bazel, although I don't know why the build only fails on CentOS 7.

The problem appears to be that on x86_64, the build requires the `-maes` compiler arg to emit native AES instructions. Not all x86_64 CPUs have this capability, but we generate it anyway and use runtime dispatch to decide if it is usable.

Internally, we use the identifier `haswell` to detect this CPU, but the opensource Bazel doesn't understand `haswell`. It understands `k8` instead.
https://github.com/abseil/abseil-cpp/blob/092ed9793a1ad0e7e418f32c057bf3159a71cd04/absl/copts/configure_copts.bzl#L64-L73

As a workaround, you can add `--copt=-maes` to your Bazel args until we patch this.

**Comment by jprider63** [comment]
Thanks @derekmauro! I'll give this a try.
