### PR TITLE
Workaround broken compilation against NDK r25

### LINKED ISSUE #1725: [Bug]: 20240722.rc1 can not be built for android ndk r25b / r25c
### Describe the issue

```
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/strings/internal/cordz_handle.cc:20:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/synchronization/mutex.h:75:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/synchronization/internal/kernel_timeout.h:30:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/time/clock.h:29:
$(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/time/time.h:1762:37: error: invalid operands to binary expression ('std::strong_ordering' and 'const std::strong_ordering')
  if (auto c = lhs_hi <=> rhs_hi; c != std::strong_ordering::equal) {
```

### Steps to reproduce the problem

See below

### What version of Abseil are you using?

20240722.rc1

### What operating system and version are you using?

Cross-compiling from linux to android

### What compiler and version are you using?

```
clang version 16.0.6
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

### What build system are you using?

[yatool](https://github.com/yandex/yatool)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by georgthegreat**
When targeting Android NDK r25 (reached EOL now, but still in some use) one gets the following error:
```
$(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/time/time.h:1762:37: error: invalid operands to binary expression ('std::strong_ordering' and 'const std::strong_ordering')
  if (auto c = lhs_hi <=> rhs_hi; c != std::strong_ordering::equal) {
```

The error indicates the lack of `operator<=>` between two `std::strong_ordering` items.
I believe that this should be controlled by `__cpp_lib_three_way_comparison` (_Three-way comparison (library support)_, see [this article](https://en.cppreference.com/w/cpp/feature_test)), not by `__cpp_impl_three_way_comparison` (which stands for _Three-way comparison (compiler support)_).

Fixes #1725.
The problem was introduced in a27662352e9caafc264747562162a8a32ef36cb9.

### CODE REVIEW

File: absl/time/time.h [hunk 1]
```diff
@@ -313,12 +313,12 @@ class Duration {
 
 // Relational Operators
 
-#ifdef __cpp_impl_three_way_comparison
+#ifdef __cpp_lib_three_way_comparison
 
 ABSL_ATTRIBUTE_CONST_FUNCTION constexpr std::strong_ordering operator<=>(
```
Comment (derekmauro) [inline absl/time/time.h:319]: My reading is that
* `__cpp_impl_three_way_comparison` is required for `<=>`
* `__cpp_lib_three_way_comparison` is required for `std::strong_ordering`

So I think this technically needs both.

File: absl/time/time.h [hunk 2]
```diff
@@ -76,9 +76,9 @@ struct timeval;
 #endif
 #include <chrono>  // NOLINT(build/c++11)
 
-#ifdef __cpp_impl_three_way_comparison
+#ifdef __cpp_lib_three_way_comparison
```
Comment (derekmauro) [inline absl/time/time.h:79]: This requires `#include <version>` for some compilers (which is annoying in my opinion).

**Review by derekmauro — CHANGES_REQUESTED** [review]
The test also needs to be fixed.

I wouldn't call this change a workaround. I think it is actually a correctness fix. I'm not sure I'm going to block the release on this given the little time we've had to test it and because it is for an EOL library.

File: absl/time/time.h (hunk 1 above)
Comment (georgthegreat) [reply absl/time/time.h:319]: Yes, technically.
But stl library is hardly capable of implementing the support if the compiler does not have it.
Hence I believe that checking `_cpp_lib` capability is enough (and the diff can be produced by a simple tool i. e. sed)

**Comment by georgthegreat** [comment]
@derekmauro, I have applies the changes suggested.
It would be better to include this changeset into release, though we can backport a patch (this would require some extra efforts regarding the patch management).

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Comment by georgthegreat** [comment]
I assume these changes are quite approved now.

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Review by vinniespina — APPROVED** [review]

**Comment by georgthegreat** [comment]
@derekmauro, let's merge it and backport to the current release.

**Comment by derekmauro** [comment]
> @derekmauro, let's merge it and backport to the current release.

Sorry, but a backport for an unsupported platform is not going to happen. These things take a lot of effort to validate and I only get to support Abseil in tiny fraction of my time. I do wish things were different, but the decision of how I get to spend my time supporting Abseil is not mine.

**Comment by georgthegreat** [comment]
Ok, I will backport the patch into our repo by myself.
Let's just merge it to make it look more legit.

**Comment by derekmauro** [comment]
It will be merged, but it is not a matter of just clicking a button. This will take some time.
